### ISSUE TITLE
Export types from package

### ISSUE THREAD

**Issue by jeron-diovis** [RenoFi/react-tooltip#270]
Please add export of `TooltipProps` / `ContentProps` / `Position` / `Trigger` types, to simplify creating wrapper components around this one. 
For now, I have to copy-paste all types from sources to my project.

**Comment by knapo** [comment]
This is an open source project, if you want to extend the functionality, please submit a PR with proposed changes.

**Comment by jeron-diovis** [comment]
thx for official confirmation that this project is dead
